### ISSUE TITLE
Implement is_complete_request

### ISSUE THREAD

**Issue by SylvainCorlay** [compiler-research/xeus-cpp#1]
The is_complete request is implemented in xeus-cling at https://github.com/jupyter-xeus/xeus-cling/blob/0.15.0/src/xinterpreter.cpp#L258-L282.

This is required for meaningful usage of xeus-cpp in a Jupyter console.

For this purpose, we would need a counterpart to cling's input validator.

**Comment by vgvassilev** [comment]
Let's cc @sunho who is actively on the related feature in clang-repl: [D143142](https://reviews.llvm.org/D143142), [D143144](https://reviews.llvm.org/D143144) and [D143148](https://reviews.llvm.org/D143148).
