### ISSUE TITLE
Drop the dependency on xtl

### ISSUE THREAD

**Issue by vgvassilev** [compiler-research/xeus-cpp#108]
We use xtl only for `xtl::prefix_path`. Let's drop this compile-time dependency.

**Comment by mcbarton** [comment]
Does this have any relation to this issue https://github.com/compiler-research/xeus-cpp/issues/54 ? A PR that fixes this issue should fix the other.

**Comment by anutosh491** [comment]
Ohh correct yeah. They look related. Is the goal for both the issues same ?
