### ISSUE TITLE
Add Tests for all XX_request methods in test_interpreter.cpp 

### ISSUE THREAD

**Issue by anutosh491** [compiler-research/xeus-cpp#114]
I think now, for a start we have some implementation for all request methods.
We also have tests for some of them and we can finish the others I guess

- [x] execute_request
- [x] inspect_request
- [x] complete_request
- [x] is_complete_request
- [x] kernel_info_request
- [x] shutdown_request

**Comment by anutosh491** [comment]
cc @tharun571 you might be interested to cover some of these.

**Comment by tharun571** [comment]
Writing tests for other files right now. Is it fine if I get on this after that?

**Comment by anutosh491** [comment]
Yeah no issues at all. Just thought of making a note of what we've covered and what we should be addressing.

**Comment by anutosh491** [comment]
This issue can now we closed as we've added basic tests for all request methods through #116 and #124
