### ISSUE TITLE
Implement inspect request

### ISSUE THREAD

**Issue by SylvainCorlay** [compiler-research/xeus-cpp#5]
When using the contextual help panel in e.g. JupyterLab, an inspect request is sent at every key stroke to populate the contextual help with the docstring of the latest item in the expression being typed.

This should presumably use the same approach as the implementation of the help magic `?` in xeus-cling, although the retrieval of the type would be done differently.

**Comment by vgvassilev** [comment]
This was implemented in https://github.com/compiler-research/xeus-cpp/pull/21. Let's consider the issue resolved.
