### ISSUE TITLE
Remove the PREFIX from generated binaries

### ISSUE THREAD

**Issue by SylvainCorlay** [compiler-research/xeus-cpp#54]
We pass the install prefix as a compile time definition for the tag files, making relocation less easy (via the `XCPP_TAGFILES_DIR` compile time definition).

We should rather use `xtl::prefix_path` at runtime to prevent the need for binary relocation.

This issue also applies to xeus-cling.

**Comment by vgvassilev** [comment]
I was thinking if we could rely on the environment here somehow. That way we can have one less dependency.

**Comment by JohanMabille** [comment]
this function has been moved to `xeus`, so we should be able to use it without reintroducing the xtl dependency.
