### ISSUE TITLE
Code Coverage report not uploading

### ISSUE THREAD

**Issue by mcbarton** [compiler-research/xeus-cpp#68]
If you looking at the ci workflow at the moment it has the error on the job which does the coverage
Error: Codecov token not found. Please provide Codecov token with -t flag.

The  report is generated but is unable to upload due to a missing token. This is not something I am able to fix. Can one of @alexander-penev @JohanMabille @vgvassilev @anutosh491  add the token where it is needed in the settings, and adjust the workflow accordingly to fix?

See https://docs.codecov.com/docs/adding-the-codecov-token for details about the token.

See https://github.com/compiler-research/xeus-cpp/actions/runs/9021481520/job/24788910894#step:13:33 for an example workflow showing the error.

**Comment by vgvassilev** [comment]
Ah, ok, now I remember. I did that for clad and will do it tomorrow for this repo.
