### ISSUE TITLE
Add Developers' Documentation

### ISSUE THREAD

**Issue by vgvassilev** [compiler-research/xeus-cpp#7]
We should add some developers' documentation on how to start development in the project locally. I believe a lot of the folks with `clang-repl` background will have trouble set up the infrastructure locally allowing them to add improvements.

**Comment by SylvainCorlay** [comment]
Is the information to install from source insufficient?

**Comment by vgvassilev** [comment]
It is sufficient to build it, however, if you want to start hacking it is not. For example, I think we need to explain how to set up a debug build, and how to configure gdb to be able to debug the already spawned process from jupyter. There were a few gdb tricks one needed to do.

**Comment by vgvassilev** [comment]
@tharun571, could you take care of this issue? You seem to gone through that process recently?

**Comment by tharun571** [comment]
Okay, will do. I'll add the debug documentation.
