### ISSUE TITLE
Upgrade to latest xeus 3.2

### ISSUE THREAD

**Issue by JohanMabille** [compiler-research/xeus-cpp#94]
The current requirement of xeus in CMakeLists.txt is 3.0.5. This should be upgraded ot the lates 3 version.

**Comment by mcbarton** [comment]
@JohanMabille Is this issue about upgrading to use xeus 3.2 or about upgrading he cmake minimum version to 3.2? Its not clear from the description. Let me know and I will then tackle this issue.

**Comment by vgvassilev** [comment]
> @JohanMabille Is this issue about upgrading to use xeus 3.2 or about upgrading he cmake minimum version to 3.2? Its not clear from the description. Let me know and I will then tackle this issue.

Yes, that's what it is.
